//-----------------------------------------------------------------------------
// piwi, 2018
//
// This code is licensed to you under the terms of the GNU GPL, version 2 or,
// at your option, any later version. See the LICENSE.txt file for the text of
// the license.
//-----------------------------------------------------------------------------
// Version information on fpga images
//
// This file is generated by fpga_compress. Don't edit!
//-----------------------------------------------------------------------------


const int fpga_bitstream_num = 1;
const char* const fpga_version_information[1] = {
	"fpga_all.bit built for 3s250evq100 on 2018/12/09 at 16:45:46"
};
